import os
from dotenv import load_dotenv

load_dotenv()

SENSORE_LOG_ACTIVITY = os.getenv("SENSORE_LOG_ACTIVITY")

MYSQL_HOST_STAGING = os.getenv("MYSQL_HOST_STAGING")
MYSQL_USER_STAGING= os.getenv("MYSQL_USER_STAGING")
MYSQL_PASSWORD_STAGING = os.getenv("MYSQL_PASSWORD_STAGING")
MYSQL_DATABASE_STAGING = os.getenv("MYSQL_DATABASE_STAGING")

MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")


ENV_MODE = os.getenv("ENV_MODE")
MYSQL_PORT = int(os.getenv("MYSQL_PORT", 3306))
MYSQL_SSL_REQUIRED = os.getenv("MYSQL_SSL_REQUIRED", "true").lower() == "true"
